// <auto-generated />
using System;
using CineTurbo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineTurbo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501164030_SeedFilmes")]
    partial class SeedFilmes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CineTurbo.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<int>("AvaliacaoImdb")
                        .HasColumnType("int");

                    b.Property<int>("AvaliacaoTomates")
                        .HasColumnType("int");

                    b.Property<string>("Duracao")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Sinopse")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CineTurboDB");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avaliacao = 5,
                            AvaliacaoImdb = 87,
                            AvaliacaoTomates = 88,
                            Duracao = "2h 16min",
                            Foto = "matrix.jpg",
                            Genero = "Ficção Científica",
                            Lancamento = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Matrix",
                            Sinopse = "Um hacker descobre a verdade sobre sua realidade."
                        },
                        new
                        {
                            Id = 2,
                            Avaliacao = 5,
                            AvaliacaoImdb = 88,
                            AvaliacaoTomates = 91,
                            Duracao = "2h 58min",
                            Foto = "sociedade-do-anel.jpg",
                            Genero = "Fantasia",
                            Lancamento = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "O Senhor dos Anéis: A Sociedade do Anel",
                            Sinopse = "Um hobbit embarca em uma jornada épica para destruir um anel maligno."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
